// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb71r7aKLVL1CJ6xY8i2RZLQgPk7KEkq0',
    appId: '1:504832290563:web:482831c7c8a7b15f910336',
    messagingSenderId: '504832290563',
    projectId: 'chat-app-3b28e',
    authDomain: 'chat-app-3b28e.firebaseapp.com',
    storageBucket: 'chat-app-3b28e.firebasestorage.app',
    measurementId: 'G-N6F3CH1SK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD19nrlca7ZhsU0AzGP6vqLzbeVReVrbxw',
    appId: '1:504832290563:android:9ef912ac35d9e45e910336',
    messagingSenderId: '504832290563',
    projectId: 'chat-app-3b28e',
    storageBucket: 'chat-app-3b28e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4WcO2fXkVLg9HQXzVcfUsN9-GSvrmu2g',
    appId: '1:504832290563:ios:1afe9ac9bef99586910336',
    messagingSenderId: '504832290563',
    projectId: 'chat-app-3b28e',
    storageBucket: 'chat-app-3b28e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4WcO2fXkVLg9HQXzVcfUsN9-GSvrmu2g',
    appId: '1:504832290563:ios:1afe9ac9bef99586910336',
    messagingSenderId: '504832290563',
    projectId: 'chat-app-3b28e',
    storageBucket: 'chat-app-3b28e.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb71r7aKLVL1CJ6xY8i2RZLQgPk7KEkq0',
    appId: '1:504832290563:web:7eed62a9ede5eb7f910336',
    messagingSenderId: '504832290563',
    projectId: 'chat-app-3b28e',
    authDomain: 'chat-app-3b28e.firebaseapp.com',
    storageBucket: 'chat-app-3b28e.firebasestorage.app',
    measurementId: 'G-7FVDW4D4GZ',
  );

}